CREATE TABLE `ncr`.`msgs` (`sno` INT NOT NULL AUTO_INCREMENT , `msg` TEXT NOT NULL , `room` TEXT NOT NULL , `ip` TEXT NOT NULL , `ctime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`sno`)) ENGINE = InnoDB;

CREATE TABLE `ncr`.`rooms` (`sno` INT NOT NULL AUTO_INCREMENT , `roomname` TEXT NOT NULL , `ctime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`sno`)) ENGINE = InnoDB;
​
